name: Build .NET Framework version

on:  
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore ./WinForms/Truesec.Decryptors.netfx.sln

      - name: Build Solution
        run: |
          msbuild.exe ./WinForms/Truesec.Decryptors.netfx.sln /p:platform="Any CPU" /p:configuration="Release"
