name: Build .NET Core version

on:  
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore ./WinForms/Truesec.Decryptors.sln

      - name: Build Solution
        run: |
          dotnet build ./WinForms/Truesec.Decryptors.sln -c Release
